### ISSUE TITLE
Question about Gemini image input

### ISSUE THREAD

**Issue by JY-Ou** [Xiaohao-Xu/Customizable-VLM#1]
In main_gemini.py the input to gemini seems to be only defect_img, good_img is not input to the model, but the text prompt is fixed format, such as the first picture is normal, please judge whether the second picture is used abnormally. Then gemini only input defect_img text prompt does not change no effect?

**Comment by BrianChen1129** [comment]
Sorry for the confusion. Our final quantitative results for Gemini leverage the reference image. We have purified the code and added some comments to it. Feel free to reach out if there are still any questions. Thanks!
